-- Миграция: Добавление таблицы шаблонов таблиц
-- Дата: 2024-12-18

-- Создание таблицы шаблонов
CREATE TABLE sheet_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100) NOT NULL COMMENT 'Категория шаблона (hotel, finance, project, etc.)',
    structure JSON NOT NULL COMMENT 'JSON структура таблицы: заголовки, примеры данных, форматирование',
    row_count INT DEFAULT 100,
    column_count INT DEFAULT 26,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_templates_category (category),
    INDEX idx_templates_active (is_active)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Добавление поля template_id в таблицу sheets
ALTER TABLE sheets ADD COLUMN template_id INT DEFAULT NULL COMMENT 'ID шаблона, на основе которого создана таблица';
ALTER TABLE sheets ADD INDEX idx_sheets_template (template_id);

-- Добавление поля source_sheet_id для связи между таблицами (отчеты ссылаются на журналы)
ALTER TABLE sheets ADD COLUMN source_sheet_id INT DEFAULT NULL COMMENT 'ID исходной таблицы для автоматического заполнения (используется в отчетах)';
ALTER TABLE sheets ADD INDEX idx_sheets_source (source_sheet_id);
ALTER TABLE sheets ADD FOREIGN KEY (source_sheet_id) REFERENCES sheets(id) ON DELETE SET NULL;

-- Вставка шаблона "Журнал заселения DMD Cottage"
INSERT INTO sheet_templates (name, description, category, structure, row_count, column_count) VALUES
('Журнал заселения DMD Cottage', 'Журнал учета заселения и выселения гостей коттеджа', 'hotel', 
JSON_OBJECT(
    'headers', JSON_ARRAY(
        JSON_OBJECT('row', 0, 'column', 0, 'value', 'Месяц', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 1, 'value', 'Дата заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 2, 'value', 'Кол-во дней', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 3, 'value', 'Дата выселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 4, 'value', 'ФИО', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 5, 'value', 'Телефон', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 6, 'value', 'Общая сумма проживания', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 7, 'value', 'Предоплата (сумма аванса)', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 8, 'value', 'Доплата за проживание в день заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 9, 'value', 'Статус дома', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 10, 'value', 'Источник', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 11, 'value', 'Комментарий по оплате и проживанию', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd')),
        JSON_OBJECT('row', 0, 'column', 12, 'value', 'Комментарии по оплате и проживанию в день заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e3f2fd'))
    ),
    -- 'sampleData', JSON_ARRAY(
    --     JSON_OBJECT('row', 1, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 1, 'column', 1, 'value', '01.01.2025'),
    --     JSON_OBJECT('row', 1, 'column', 2, 'value', ''),
    --     JSON_OBJECT('row', 1, 'column', 3, 'value', '03.01.2025'),
    --     JSON_OBJECT('row', 1, 'column', 4, 'value', 'Иван'),
    --     JSON_OBJECT('row', 1, 'column', 5, 'value', '952 894-02-80'),
    --     JSON_OBJECT('row', 1, 'column', 6, 'value', '280 000,00'),
    --     JSON_OBJECT('row', 1, 'column', 7, 'value', '140 000,00'),
    --     JSON_OBJECT('row', 1, 'column', 8, 'value', '140 000,00'),
    --     JSON_OBJECT('row', 1, 'column', 9, 'value', 'Проживают'),
    --     JSON_OBJECT('row', 1, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 1, 'column', 11, 'value', '280к/140п (21.10. в 11:33) доплата 140.000 до 16 ГОСТЕЙ'),
    --     JSON_OBJECT('row', 1, 'column', 12, 'value', 'Ключи переданы, документы проверены'),
    --     JSON_OBJECT('row', 2, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 2, 'column', 1, 'value', '02.01.2025'),
    --     JSON_OBJECT('row', 2, 'column', 2, 'value', '-45 659,00'),
    --     JSON_OBJECT('row', 2, 'column', 3, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 4, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 5, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 6, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 7, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 8, 'value', '0,00'),
    --     JSON_OBJECT('row', 2, 'column', 9, 'value', 'Проживают'),
    --     JSON_OBJECT('row', 2, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 11, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 12, 'value', ''),
    --     JSON_OBJECT('row', 3, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 3, 'column', 1, 'value', '03.01.2025'),
    --     JSON_OBJECT('row', 3, 'column', 2, 'value', '2,00'),
    --     JSON_OBJECT('row', 3, 'column', 3, 'value', '05.01.2025'),
    --     JSON_OBJECT('row', 3, 'column', 4, 'value', 'Мария'),
    --     JSON_OBJECT('row', 3, 'column', 5, 'value', '999 833-04-80'),
    --     JSON_OBJECT('row', 3, 'column', 6, 'value', '100 000,00'),
    --     JSON_OBJECT('row', 3, 'column', 7, 'value', '50 000,00'),
    --     JSON_OBJECT('row', 3, 'column', 8, 'value', '50 000,00'),
    --     JSON_OBJECT('row', 3, 'column', 9, 'value', 'Выс/Зас'),
    --     JSON_OBJECT('row', 3, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 3, 'column', 11, 'value', '100к/50п (10.11 в 11:13) доплата 50.000 до 16 ГОСТЕЙ'),
    --     JSON_OBJECT('row', 3, 'column', 12, 'value', 'Требуется дополнительная уборка'),
    --     JSON_OBJECT('row', 4, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 4, 'column', 1, 'value', '04.01.2025'),
    --     JSON_OBJECT('row', 4, 'column', 2, 'value', '-45 661,00'),
    --     JSON_OBJECT('row', 4, 'column', 3, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 4, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 5, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 6, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 7, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 8, 'value', '0,00'),
    --     JSON_OBJECT('row', 4, 'column', 9, 'value', 'Проживают'),
    --     JSON_OBJECT('row', 4, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 11, 'value', ''),
    --     JSON_OBJECT('row', 4, 'column', 12, 'value', ''),
    --     JSON_OBJECT('row', 5, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 5, 'column', 1, 'value', '05.01.2025'),
    --     JSON_OBJECT('row', 5, 'column', 2, 'value', '1,00'),
    --     JSON_OBJECT('row', 5, 'column', 3, 'value', '06.01.2025'),
    --     JSON_OBJECT('row', 5, 'column', 4, 'value', 'Венера'),
    --     JSON_OBJECT('row', 5, 'column', 5, 'value', '905 745-64-80'),
    --     JSON_OBJECT('row', 5, 'column', 6, 'value', '50 000,00'),
    --     JSON_OBJECT('row', 5, 'column', 7, 'value', '25 000,00'),
    --     JSON_OBJECT('row', 5, 'column', 8, 'value', '25 000,00'),
    --     JSON_OBJECT('row', 5, 'column', 9, 'value', 'Выс/Зас'),
    --     JSON_OBJECT('row', 5, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 5, 'column', 11, 'value', '50К/25П( 13.12 в 13:45) доплата 25.000р. до 16 гостей.'),
    --     JSON_OBJECT('row', 5, 'column', 12, 'value', 'Проверить санузел после уборки'),
    --     JSON_OBJECT('row', 6, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 6, 'column', 1, 'value', '06.01.2025'),
    --     JSON_OBJECT('row', 6, 'column', 2, 'value', '2,00'),
    --     JSON_OBJECT('row', 6, 'column', 3, 'value', '08.01.2025'),
    --     JSON_OBJECT('row', 6, 'column', 4, 'value', 'Сергей'),
    --     JSON_OBJECT('row', 6, 'column', 5, 'value', '985 915-77-80'),
    --     JSON_OBJECT('row', 6, 'column', 6, 'value', '100 000,00'),
    --     JSON_OBJECT('row', 6, 'column', 7, 'value', '50 000,00'),
    --     JSON_OBJECT('row', 6, 'column', 8, 'value', '50 000,00'),
    --     JSON_OBJECT('row', 6, 'column', 9, 'value', 'Выс/Зас'),
    --     JSON_OBJECT('row', 6, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 6, 'column', 11, 'value', '100к/50п (10.12. в 16:40) доплата 50.000 до 16чел.\nСпа-зона, собака, возможно еще баня'),
    --     JSON_OBJECT('row', 6, 'column', 12, 'value', 'Подготовить спа-зону и место для собаки'),
    --     JSON_OBJECT('row', 7, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 7, 'column', 1, 'value', '07.01.2025'),
    --     JSON_OBJECT('row', 7, 'column', 2, 'value', '-45 664,00'),
    --     JSON_OBJECT('row', 7, 'column', 3, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 4, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 5, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 6, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 7, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 8, 'value', '0,00'),
    --     JSON_OBJECT('row', 7, 'column', 9, 'value', 'Проживают'),
    --     JSON_OBJECT('row', 7, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 11, 'value', ''),
    --     JSON_OBJECT('row', 7, 'column', 12, 'value', ''),
    --     JSON_OBJECT('row', 8, 'column', 0, 'value', 'Январь 2025'),
    --     JSON_OBJECT('row', 8, 'column', 1, 'value', '08.01.2025'),
    --     JSON_OBJECT('row', 8, 'column', 2, 'value', '1,00'),
    --     JSON_OBJECT('row', 8, 'column', 3, 'value', '09.01.2025'),
    --     JSON_OBJECT('row', 8, 'column', 4, 'value', 'Талян'),
    --     JSON_OBJECT('row', 8, 'column', 5, 'value', '980 489-80-80'),
    --     JSON_OBJECT('row', 8, 'column', 6, 'value', '24 000,00'),
    --     JSON_OBJECT('row', 8, 'column', 7, 'value', '12 000,00'),
    --     JSON_OBJECT('row', 8, 'column', 8, 'value', '12 000,00'),
    --     JSON_OBJECT('row', 8, 'column', 9, 'value', 'Выс/Зас'),
    --     JSON_OBJECT('row', 8, 'column', 10, 'value', ''),
    --     JSON_OBJECT('row', 8, 'column', 11, 'value', '2 гостей'),
    --     JSON_OBJECT('row', 8, 'column', 12, 'value', 'Небольшая компания, минимум удобств')
    -- ),
    'columnWidths', JSON_OBJECT(
        '0', 120, '1', 120, '2', 100, '3', 120, '4', 150, '5', 130, 
        '6', 180, '7', 180, '8', 200, '9', 120, '10', 100, '11', 300, '12', 250
    )
), 50, 13);

-- Вставка шаблона "Отчет заселения/выселения"
INSERT INTO sheet_templates (name, description, category, structure, row_count, column_count) VALUES
('Отчет заселения/выселения DMD Cottage', 'Ежедневный отчет о заселениях и выселениях на конкретную дату', 'hotel', 
JSON_OBJECT(
    'headers', JSON_ARRAY(
        JSON_OBJECT('row', 0, 'column', 0, 'value', '30.03.2025', 'format', JSON_OBJECT('fontWeight', 'bold', 'fontSize', '16px', 'textAlign', 'center')),
        JSON_OBJECT('row', 0, 'column', 2, 'value', 'Выселение', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#ffebee', 'textAlign', 'center')),
        JSON_OBJECT('row', 0, 'column', 6, 'value', 'Заселение', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8', 'textAlign', 'center')),
        JSON_OBJECT('row', 1, 'column', 0, 'value', 'Адрес', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#f5f5f5')),
        JSON_OBJECT('row', 1, 'column', 1, 'value', 'Статус дома', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#f5f5f5')),
        JSON_OBJECT('row', 1, 'column', 2, 'value', 'ФИО', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#ffebee')),
        JSON_OBJECT('row', 1, 'column', 3, 'value', 'Телефон', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#ffebee')),
        JSON_OBJECT('row', 1, 'column', 4, 'value', 'Комментарий из журнала заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#ffebee')),
        JSON_OBJECT('row', 1, 'column', 5, 'value', 'Время выселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#ffebee')),
        JSON_OBJECT('row', 1, 'column', 6, 'value', 'ФИО', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 7, 'value', 'Телефон', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 8, 'value', 'Время заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 9, 'value', 'Дата выселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 10, 'value', 'Кол-во дней', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 11, 'value', 'Общая сумма проживания', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 12, 'value', 'Предоплата (сумма аванса)', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 13, 'value', 'Доплата\nза проживание\nв день заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 14, 'value', 'Комментарий из журнала заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 15, 'value', 'Комментарии по оплате и проживанию в день заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8')),
        JSON_OBJECT('row', 1, 'column', 16, 'value', 'Комментарии по оплате и проживанию в день заселения', 'format', JSON_OBJECT('fontWeight', 'bold', 'backgroundColor', '#e8f5e8'))
    ),
    -- 'sampleData', JSON_ARRAY(
    --     JSON_OBJECT('row', 2, 'column', 0, 'value', '29'),
    --     JSON_OBJECT('row', 2, 'column', 1, 'value', 'Выс/Зас'),
    --     JSON_OBJECT('row', 2, 'column', 2, 'value', 'Дмитрий'),
    --     JSON_OBJECT('row', 2, 'column', 3, 'value', '916 747 52 80'),
    --     JSON_OBJECT('row', 2, 'column', 4, 'value', '16-17 чел , 37000 общ, 18000 переведут , к оплате 19000. Залог 12000\n37к/18п (11.03. в 21:56)\nДоплата 19.000, баня 4.500, залог 12.000 - Хасият'),
    --     JSON_OBJECT('row', 2, 'column', 5, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 6, 'value', 'Екатерина '),
    --     JSON_OBJECT('row', 2, 'column', 7, 'value', '986 990 79 80'),
    --     JSON_OBJECT('row', 2, 'column', 8, 'value', ''),
    --     JSON_OBJECT('row', 2, 'column', 9, 'value', '31.03.2025'),
    --     JSON_OBJECT('row', 2, 'column', 10, 'value', '1,00'),
    --     JSON_OBJECT('row', 2, 'column', 11, 'value', '11 050,00'),
    --     JSON_OBJECT('row', 2, 'column', 12, 'value', '4 550,00'),
    --     JSON_OBJECT('row', 2, 'column', 13, 'value', '6 500,00'),
    --     JSON_OBJECT('row', 2, 'column', 14, 'value', '6 гостей  будет собачка ( до 4 кг.)'),
    --     JSON_OBJECT('row', 2, 'column', 15, 'value', 'забронировали ВРЕМЯ бани 30.03.25 на два  часа с  с 17:00 до 19:00  ( допл. 6.500+ 3.000 баня + 3.000 собака + 12.000 залог  Надежда НАЛ.)'),
    --     JSON_OBJECT('row', 2, 'column', 16, 'value', 'Ключи переданы, документы проверены')
    -- ),
    'columnWidths', JSON_OBJECT(
        '0', 80, '1', 120, '2', 150, '3', 130, '4', 250, '5', 120, 
        '6', 150, '7', 130, '8', 120, '9', 120, '10', 100, '11', 150, 
        '12', 150, '13', 180, '14', 250, '15', 300, '16', 280
    )
), 30, 17); 